### ISSUE TITLE
How do you get the request body?

### ISSUE THREAD

**Issue by andersea** [MattCollins84/restly#8]
If I create a post or put handler. How can I get the body of the posted message from the library callback?
```
function getToken(opts, callback){
    // How do I get the body?
	callback(null, {your_params: opts});
}

module.exports = {
	getToken: getToken
}
```

**Comment by MattCollins84** [comment]
At present, there is no way of getting the body. You can however get the POST/PUT request vars from the ops parameter.

This was a bit of an oversight on my side as it was not a use case in the project I built restly for. I do not have time to make this change at the moment, but feel free to submit a pull request!

**Comment by andersea** [comment]
Thanks for your answer.
